Kasunika wickramarachchi
Yohombu/StudentApp pull request #1
Opened 2024-07-05 16:56 UTC by kasunikahansamali

Model Added

2024-07-12 08:09 UTC, ishara94 commented on StudentApp/Controllers/StudentController.cs
> +        //public IActionResult Index()
remove comment content

2024-07-12 08:09 UTC, ishara94 commented on StudentApp/Controllers/StudentController.cs
> +            _db = db;
use proper variable name

2024-07-12 08:09 UTC, ishara94 commented on StudentApp/Controllers/StudentsController.cs
> +            _istudentAppRepository = studentAppRepository;
use camel case

2024-07-12 08:09 UTC, ishara94 commented on StudentApp/Controllers/StudentsController.cs
> +                return BadRequest(ModelState);
ModelState instaed this use a pass sting message

2024-07-12 08:09 UTC, ishara94 commented on StudentApp/Controllers/StudentsController.cs
> +                Name = model.Name,
Move this to private message

2024-07-12 08:12 UTC, AmilaKR commented on StudentApp/Controllers/StudentsController.cs
> +        private readonly IStudentAppRepository _istudentAppRepository;
don't use the interface name as the variable name, 
use like "_studentAppRepository" instead of "_istudentAppRepository"

2024-07-12 08:18 UTC, AmilaKR requested changes
Please change the target branch to the Develop branch

2024-07-30 05:41 UTC, closed without merging

2024-07-30 05:41 UTC, kasunikahansamali commented
Resolved code added